### ISSUE TITLE
ros2 run demo_nodes_cpp talker with rmw_ecal_proto_cpp runtime error.

### ISSUE THREAD

**Issue by ZhenshengLee** [continental/rmw_ecal#19]
## Env

- ubuntu 20.04
- ros2 foxy (apt install)
- ecal latest(apt install)
 - ecal 5.8.10-1ppa1~focal
 - libecal-2.0-1:amd64 3.36.5-0ubuntu1
- rmw_ecal master 1.0.0(git clone)
- rosidl_typesupport_protobuf 1.0.0 (git clone)

## error info

```sh
zs@zs-3630:~$ RMW_IMPLEMENTATION=rmw_ecal_proto_cpp ros2 run demo_nodes_cpp talker
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported type support.
```

Are there any configuration missing?

Thanks.

**Comment by brakmic-aleksandar** [comment]
Have you built and sourced ROS2 messages (ex. rcl_interfaces)? They need to be built so typesupport can generate protobuf code for them.

**Comment by ZhenshengLee** [comment]
> Have you built and sourced ROS2 messages (ex. rcl_interfaces)? They need to be built so typesupport can generate protobuf code for them.

No, I did not. I will take rcl_interface source code into my workspace and give it more tests.

Thanks.

**Comment by ZhenshengLee** [comment]
add runtime error call stack.

```sh
libc.so.6!__GI_raise(int sig) (/build/glibc-YbNSs7/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:50)
libc.so.6!__GI_abort() (/build/glibc-YbNSs7/glibc-2.31/stdlib/abort.c:79)
libstdc++.so.6![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libstdc++.so.6!std::terminate() (Unknown Source:0)
libstdc++.so.6!__cxa_throw (Unknown Source:0)
librmw_ecal_proto_cpp.so!eCAL::rmw::ProtoTypeSupportFactory::Create(rosidl_message_type_support_t const*) const (Unknown Source:0)
librmw_ecal_shared_cpp.so!eCAL::rmw::rmw_create_publisher(char const*, eCAL::rmw::TypesupportFactory const&, rmw_node_t const*, rosidl_message_type_support_t const*, char const*, rmw_qos_profile_t const*, rmw_publisher_options_t const*) (Unknown Source:0)
librmw_ecal_proto_cpp.so!rmw_create_publisher (Unknown Source:0)
librcl.so!rcl_publisher_init (Unknown Source:0)
librcl.so!rcl_logging_rosout_init_publisher_for_node (Unknown Source:0)
librcl.so!rcl_node_init (Unknown Source:0)
librclcpp.so!rclcpp::node_interfaces::NodeBase::NodeBase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<rclcpp::Context>, rcl_node_options_t const&, bool, bool) (Unknown Source:0)
librclcpp.so!rclcpp::Node::Node(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::NodeOptions const&) (Unknown Source:0)
librclcpp.so!rclcpp::Node::Node(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::NodeOptions const&) (Unknown Source:0)
libtopics_library.so!demo_nodes_cpp::Talker::Talker(rclcpp::NodeOptions const&) (Unknown Source:0)
libtopics_library.so!rclcpp_components::NodeFactoryTemplate<demo_nodes_cpp::Talker>::create_node_instance(rclcpp::NodeOptions const&) (Unknown Source:0)
main (Unknown Source:0)
```

**Comment by ZhenshengLee** [comment]
the runtime error detail

```sh
zs@zs-3630:~/zs_ws/ga2_ws/src/ga_ros2$ RMW_IMPLEMENTATION=rmw_ecal_proto_cpp ros2 run demo_nodes_cpp talker
terminate called after throwing an instance of 'std::runtime_error'
  what():  Handle's typesupport identifier (rosidl_typesupport_c) is not supported by this library
, at /home/zs/zs_ws/ga2_ws/src/ga_ros2/ga_deps/rosidl_typesupport/rosidl_typesupport_c/src/type_support_dispatch.hpp:126

```

**Comment by ZhenshengLee** [comment]
After I import `rosidl_defaults` source code, the ws can be compiled. 

And there is another runtime error in `rosidl_typesupport/rosidl_typesupport_cpp/src/type_support_dispatch.hpp`  when openning so file about protobuf.

```sh
[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: builtin_interfaces/msg/Duration.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
```

Could you give this a tutorial? @brakmic-aleksandar 

Thanks.

**Comment by ZhenshengLee** [comment]
After I import protobuf source compile with -fPIC, I ran another runtime error.

So, more code, more bugs? @brakmic-aleksandar @rex-schilasky 

Both ecal_dynamic_cpp and ecal_proto_cpp cannot be used in dashing or foxy.

- ecal_dynamic_cpp cannot be used due to **ros2cli tool unaviable**.
- ecal_proto_cpp cannot be used due to **runtime crash** without reason.

**Comment by rex-schilasky** [comment]
Thank your for reporting and all the effort you invest. Please let us check that with care. As eCAL maintainer I'm focused on keeping eCAL productive. Let's see what @brakmic-aleksandar can figure out.

**Comment by brakmic-aleksandar** [comment]
I've just tried it using Ubuntu18.4/dashing and it seemed to be working fine.
I've also tried it on Ubuntu20.4/foxy and the error did appear, i'll see what can i do about it.

**Comment by ZhenshengLee** [comment]
> I've just tried it using Ubuntu18.4/dashing and it seemed to be working fine.
> I've also tried it on Ubuntu20.4/foxy and the error did appear, i'll see what can i do about it.

In ubuntu18.04/eloquent, there are compiling issues with protobuf version.

```sh
/home/nvidia/zs_ws/ga2_ws/src/ga_ros2/colcon/build/lifecycle_msgs/rosidl_typesupport_protobuf_c/lifecycle_msgs/srv/detail/get_available_states__type_support.cpp: In function ‘bool lifecycle_msgs::srv::typesupport_protobuf_c::convert_to_ros(const lifecycle_msgs::srv::pb::GetAvailableStates_Response&, lifecycle_msgs__srv__GetAvailableStates_Response&)’:
/home/nvidia/zs_ws/ga2_ws/src/ga_ros2/colcon/build/lifecycle_msgs/rosidl_typesupport_protobuf_c/lifecycle_msgs/srv/detail/get_available_states__type_support.cpp:183:75: error: no match for ‘operator[]’ (operand types are ‘const google::protobuf::RepeatedPtrField<lifecycle_msgs::msg::pb::State>’ and ‘int’)
       ::lifecycle_msgs::msg::typesupport_protobuf_c::convert_to_ros(pb_arr[i], ros_arr[i]);
                                                                           ^
/home/nvidia/zs_ws/ga2_ws/src/ga_ros2/colcon/build/lifecycle_msgs/rosidl_typesupport_protobuf_c/lifecycle_msgs/srv/detail/get_available_transitions__type_support.cpp: In function ‘bool lifecycle_msgs::srv::typesupport_protobuf_c::convert_to_ros(const lifecycle_msgs::srv::pb::GetAvailableTransitions_Response&, lifecycle_msgs__srv__GetAvailableTransitions_Response&)’:
/home/nvidia/zs_ws/ga2_ws/src/ga_ros2/colcon/build/lifecycle_msgs/rosidl_typesupport_protobuf_c/lifecycle_msgs/srv/detail/get_available_transitions__type_support.cpp:183:75: error: no match for ‘operator[]’ (operand types are ‘const google::protobuf::RepeatedPtrField<lifecycle_msgs::msg::pb::TransitionDescription>’ and ‘int’)
       ::lifecycle_msgs::msg::typesupport_protobuf_c::convert_to_ros(pb_arr[i], ros_arr[i]);
                                                                           ^
make[2]: *** [CMakeFiles/lifecycle_msgs__rosidl_typesupport_protobuf_c.dir/rosidl_typesupport_protobuf_c/lifecycle_msgs/srv/detail/get_available_states__type_support.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/lifecycle_msgs__rosidl_typesupport_protobuf_c.dir/rosidl_typesupport_protobuf_c/lifecycle_msgs/srv/detail/get_available_transitions__type_support.cpp.o] Error 1
make[1]: *** [CMakeFiles/lifecycle_msgs__rosidl_typesupport_protobuf_c.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
---
Failed   <<< lifecycle_msgs [43.7s, exited with code 2]
Aborted  <<< rosgraph_msgs [9.51s]
Aborted  <<< action_msgs [11.3s]
Aborted  <<< rcl_interfaces [14.0s]

```

So, what's the protobuf version policy,  in 18.04 the default version from apt is v3.0.0

```sh
nvidia@Xavier:~/zs_ws/ga2_ws/src/ga_ros2$ dpkg -l | grep protobuf
ii  libmirprotobuf3:arm64                               0.31.1-0ubuntu1                                  arm64        Display server for Ubuntu - RPC definitions
ii  libprotobuf-dev:arm64                               3.0.0-9.1ubuntu1                                 arm64        protocol buffers C++ library (development files)
ii  libprotobuf-lite10:arm64                            3.0.0-9.1ubuntu1                                 arm64        protocol buffers C++ library (lite version)
ii  libprotobuf10:arm64                                 3.0.0-9.1ubuntu1                                 arm64        protocol buffers C++ library
ii  protobuf-compiler                                   3.0.0-9.1ubuntu1                                 arm64        compiler for protocol buffer definition files
ii  python3-protobuf                                    3.0.0-9.1ubuntu1                                 arm64        Python 3 bindings for protocol buffers

```

After installing new version of protobuf, should I recompile eCAL from source?

**Comment by brakmic-aleksandar** [comment]
You should install libprotobuf3-dev aswell. :)

**Comment by ZhenshengLee** [comment]
> libprotobuf3-dev

actually there is no `libprotobuf3-dev` installation candidate in ubuntu 18.04, see below

```sh
nvidia@Xavier:~/zs_ws/ga2_ws/src/ga_ros2$ apt-cache search libprotobuf
libprotobuf-dev - protocol buffers C++ library (development files)
libprotobuf-lite10 - protocol buffers C++ library (lite version)
libprotobuf10 - protocol buffers C++ library
libprotobuf-c-dev - Protocol Buffers C static library and headers (protobuf-c)
libprotobuf-c1 - Protocol Buffers C shared library (protobuf-c)
libprotobuf-c1-dbg - Protocol Buffers C shared library debug symbols (protobuf-c)
libprotobuf-java - Java bindings for protocol buffers
libprotobuf-java-format-java - Library to serialize protobuf messages to XML, JSON and HTML
protobuf-c-compiler - Protocol Buffers C compiler (protobuf-c)
```

**Comment by FlorianReimold** [comment]
The name of the package is libprotobuf-dev:

```
sudo apt install libprotobuf-dev
```

**Comment by ZhenshengLee** [comment]
> The name of the package is libprotobuf-dev:
> 
> ```
> sudo apt install libprotobuf-dev
> ```

You are right. @FlorianReimold 

I actually installed this package and compile error exists in my jetson ubuntu18.04 device.

> I've just tried it using Ubuntu18.4/dashing and it seemed to be working fine.

So there must be something wrong. @brakmic-aleksandar 

Thanks.

**Comment by brakmic-aleksandar** [comment]
Okay, seems it seems that protobuf 3.0 repeatable fields don't support [] member access operator, unlike later versions of, that should be fairly easy to fix.

**Comment by brakmic-aleksandar** [comment]
I've made a fix that should resolve that issue.
You can find it here https://github.com/continental/rosidl_typesupport_protobuf/tree/hotfix/older_protobuf

**Comment by ZhenshengLee** [comment]
> I've also tried it on Ubuntu20.4/foxy and the error did appear, i'll see what can i do about it.

@brakmic-aleksandar this problem still exists in foxy, any updates please?

**Comment by brakmic-aleksandar** [comment]
Sorry for a bit late response, i'm currently working on this issue.

**Comment by brakmic-aleksandar** [comment]
Sorry about late response, for now only, band-aid, solution is using latest Protobuf version instead of one that comes with Ubuntu.

**Comment by ZhenshengLee** [comment]
> Sorry about late response, for now only, band-aid, solution is using latest Protobuf version instead of one that comes with Ubuntu.

@brakmic-aleksandar 

Could you please provide installation guide of latest probutf version?

**Comment by brakmic-aleksandar** [comment]
Hmm, one way would be to build it yourself (this might be helpful https://gist.github.com/diegopacheco/cd795d36e6ebcd2537cd18174865887b).
Another possible solution would to install it via pip, or maybe some other package manager (haven't tried this)
